version: 2.1
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
           name: Build and public on docker
           command: |
              docker build .
              docker login --username=_ --password-stdin=$HEROKU_API_KEY registry.heroku.com
              heroku container:push web -app $APP_NAME
              heroku container:release web -app $APP_NAME
