version: 2.1
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
           name: Build and public on docker
           command: |
              docker build -t slimformaturasapi
              echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
              docker tag boku jcslimshady/slimformaturasapi
              docker push jcslimshady/slimformaturasapi
